[colors.bright]
black = "#585858"
blue = "#7cafc2"
cyan = "#86c1b9"
green = "#a1b56c"
magenta = "#ba8baf"
red = "#ab4642"
white = "#f8f8f8"
yellow = "#f7ca88"

[colors.cursor]
cursor = "#d8d8d8"
text = "#d8d8d8"

[colors.normal]
black = "#181818"
blue = "#7cafc2"
cyan = "#86c1b9"
green = "#a1b56c"
magenta = "#ba8baf"
red = "#ab4642"
white = "#d8d8d8"
yellow = "#f7ca88"

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[env]
TERM = "alacritty"

[font]
size = 9.5
#size = 12.5

[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Jetbrains Mono"
style = "Italic"

[font.normal]
family = "Comic Shanns Mono"
style = "Regular"

[font.offset]
x = 1
y = 0

[terminal.shell]
program = "nu"

[window]
decorations = "full"
startup_mode = "Windowed"
